//import { addressToLocations } from "esri/rest/locator/addressToLocations";
import { Adress } from '@/types/Adress';

const url =
  'https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer';

export type Address = {
  original_address: string;
  lat: number;
  lon: number;
  formatted: string;
  name: string;
  housenumber: any;
  street: string;
  postcode: string;
  district: string;
  suburb: string;
  city: string;
  state: string;
  county: string;
  country: string;
  country_code: string;
  confidence: number;
  confidence_city_level: number;
  confidence_street_level: any;
  attribution: string;
  attribution_license: string;
  attribution_url: string;
};
const spatialReference = {
    "latestWkid": 3857,
    "wkid": 102100
}


const addresses = [
  {
    original_address: 'Stockholmsvägen 1, 182 78 Stocksund',
    lat: 59.385068399999994,
    lon: 18.045389061780458,
    formatted: 'Lidl, Stockholmsvägen 1, 182 78 Danderyds kommun, Sverige',
    name: 'Lidl',
    housenumber: 1,
    street: 'Stockholmsvägen',
    postcode: '182 78',
    district: 'Stockby',
    suburb: 'Mörby',
    city: 'Danderyds kommun',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Stockholmsvägen 20, 181 50 Lidingö',
    lat: 59.3633864,
    lon: 18.1237141,
    formatted: 'Stockholmsvägen 20, 181 50 Lidingö, Sverige',
    name: '',
    housenumber: 20,
    street: 'Stockholmsvägen',
    postcode: '181 50',
    district: '',
    suburb: 'Herserud',
    city: 'Lidingö',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Enhagsvägen 24, 183 34 Täby',
    lat: 59.44002,
    lon: 18.0350218,
    formatted: 'Enhagsvägen 24, 187 40 Täby, Sverige',
    name: '',
    housenumber: 24,
    street: 'Enhagsvägen',
    postcode: '187 40',
    district: 'Sågtorp',
    suburb: 'Ella gård',
    city: 'Täby',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Sankt Eriksgatan 113, 113 43 Stockholm',
    lat: 59.346391,
    lon: 18.03972,
    formatted: 'Sankt Eriksgatan 113, 113 43 Stockholm, Sverige',
    name: '',
    housenumber: 113,
    street: 'Sankt Eriksgatan',
    postcode: '113 43',
    district: 'Vantör',
    suburb: 'Vasastaden',
    city: 'Stockholm',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.9,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenAddresses contributors',
    attribution_license: 'BSD-3-Clause License',
    attribution_url: '',
  },
  {
    original_address: 'Bibliotekstorget 2A, 171 45 Solna',
    lat: 59.3597727,
    lon: 18.0014895,
    formatted:
      'Solna stadsbibliotek, Biblioteksgången 12, 171 45 Solna kommun, Sverige',
    name: 'Solna stadsbibliotek',
    housenumber: 12,
    street: 'Biblioteksgången',
    postcode: '171 45',
    district: 'Vasalund',
    suburb: 'Råsunda',
    city: 'Solna kommun',
    state: 'Stockholm',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.378,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Saluvägen 10, 187 66 Täby',
    lat: 59.4590591,
    lon: 18.137803,
    formatted: 'Stora Coop, Saluvägen 10, 187 66 Täby kommun, Sverige',
    name: 'Stora Coop',
    housenumber: 10,
    street: 'Saluvägen',
    postcode: '187 66',
    district: '',
    suburb: 'Arninge',
    city: 'Täby kommun',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Sveavägen 59, 113 59 STOCKHOLM',
    lat: 59.3408036,
    lon: 18.0582458,
    formatted: 'Sveavägen 59, 113 59 Stockholm, Sverige',
    name: '',
    housenumber: 59,
    street: 'Sveavägen',
    postcode: '113 59',
    district: 'Norrmalms stadsdelsområde',
    suburb: 'Vasastaden',
    city: 'Stockholm',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.9,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Sibyllegatan 8, 114 42 Stockholm',
    lat: 59.335928,
    lon: 18.080403,
    formatted: 'Sibyllegatan 6A, 114 42 Stockholm, Sverige',
    name: '',
    housenumber: '6A',
    street: 'Sibyllegatan',
    postcode: '114 42',
    district: 'Vantör',
    suburb: 'Östermalm',
    city: 'Stockholm',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.63,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenAddresses contributors',
    attribution_license: 'BSD-3-Clause License',
    attribution_url: '',
  },
  {
    original_address: 'Kista Galleria, 164 91 Kista',
    lat: 59.4034402,
    lon: 17.944066,
    formatted: 'Kista Galleria, Hanstavägen 55F, 164 53 Stockholm, Sverige',
    name: 'Kista Galleria',
    housenumber: '55F',
    street: 'Hanstavägen',
    postcode: '164 53',
    district: 'Rinkeby-Kista stadsdelsområde',
    suburb: 'Kista',
    city: 'Stockholm',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: '',
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Landsvägen 47, 172 65 Sundbyberg',
    lat: 59.3610101,
    lon: 17.9692108,
    formatted: 'Lidl, Landsvägen 47, 172 65 Sundbybergs kommun, Sverige',
    name: 'Lidl',
    housenumber: 47,
    street: 'Landsvägen',
    postcode: '172 65',
    district: 'Hästhagen',
    suburb: 'Lilla Alby',
    city: 'Sundbybergs kommun',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Sankt Göransgatan 70, 112 38 Stockholm',
    lat: 59.33331,
    lon: 18.030938,
    formatted: 'Sankt Göransgatan 65, 112 38 Stockholm, Sverige',
    name: '',
    housenumber: 65,
    street: 'Sankt Göransgatan',
    postcode: '112 38',
    district: 'Vantör',
    suburb: 'Kungsholmen',
    city: 'Stockholm',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.63,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenAddresses contributors',
    attribution_license: 'BSD-3-Clause License',
    attribution_url: '',
  },
  {
    original_address: 'Djupdalsvägen 29, 192 73 Sollentuna',
    lat: 59.4453632,
    lon: 17.9504741,
    formatted: 'Djupdalsvägen, 192 54 Sollentuna kommun, Sverige',
    name: 'Djupdalsvägen',
    housenumber: '',
    street: 'Djupdalsvägen',
    postcode: '192 54',
    district: '',
    suburb: 'Häggvik',
    city: 'Sollentuna kommun',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.315,
    confidence_city_level: 0.63,
    confidence_street_level: 0.63,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Tistelvägen 21, 191 62 Sollentuna',
    lat: 59.4302914,
    lon: 17.936616090237358,
    formatted: 'Lidl, Tistelvägen 21, 191 63 Sollentuna kommun, Sverige',
    name: 'Lidl',
    housenumber: 21,
    street: 'Tistelvägen',
    postcode: '191 63',
    district: 'Vantör',
    suburb: 'Tureberg',
    city: 'Sollentuna kommun',
    state: 'Stockholm',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.63,
    confidence_city_level: 0.63,
    confidence_street_level: 0.63,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Rinkebytorget 1, 163 73 Spånga',
    lat: 59.381807,
    lon: 17.894363,
    formatted: 'Spånga, Stockholm, Sverige',
    name: 'Spånga',
    housenumber: '',
    street: '',
    postcode: '',
    district: 'Vantör',
    suburb: 'Spånga',
    city: 'Stockholm',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.25,
    confidence_city_level: 1,
    confidence_street_level: '',
    attribution: '',
    attribution_license: '',
    attribution_url: 'https://www.whosonfirst.org/docs/licenses/',
  },
  {
    original_address: 'Folkungagatan 51, 116 22 Stockholm',
    lat: 59.3144817,
    lon: 18.0747498,
    formatted: 'Folkungagatan 51, 116 22 Stockholm, Sverige',
    name: '',
    housenumber: 51,
    street: 'Folkungagatan',
    postcode: '116 22',
    district: 'Södermalms stadsdelsområde',
    suburb: 'Södermalm',
    city: 'Stockholm',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.9,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Villmanstrandsgatan 6, 164 73 Kista',
    lat: 59.4129253,
    lon: 17.918273,
    formatted: 'Villmanstrandsgatan, 164 73 Stockholm, Sverige',
    name: 'Villmanstrandsgatan',
    housenumber: '',
    street: 'Villmanstrandsgatan',
    postcode: '164 73',
    district: 'Rinkeby-Kista stadsdelsområde',
    suburb: 'Akalla',
    city: 'Stockholm',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.475,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Magnus Ladulåsgatan 3, 118 65 Stockholm',
    lat: 59.311827,
    lon: 18.059796,
    formatted: 'Magnus Ladulåsgatan 5, 118 65 Stockholm, Sverige',
    name: '',
    housenumber: 5,
    street: 'Magnus Ladulåsgatan',
    postcode: '118 65',
    district: 'Vantör',
    suburb: 'Södermalm',
    city: 'Stockholm',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.63,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenAddresses contributors',
    attribution_license: 'BSD-3-Clause License',
    attribution_url: '',
  },
  {
    original_address: 'Bromstensvägen 158, 163 55 Spånga',
    lat: 59.378074,
    lon: 17.907764,
    formatted: 'Bromstensvägen 158, 163 55 Stockholm, Sverige',
    name: '',
    housenumber: 158,
    street: 'Bromstensvägen',
    postcode: '163 55',
    district: 'Vantör',
    suburb: 'Spånga',
    city: 'Stockholm',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenAddresses contributors',
    attribution_license: 'BSD-3-Clause License',
    attribution_url: '',
  },
  {
    original_address: 'Liljeholmstorget 44, 117 61 Stockholm',
    lat: 59.3100245,
    lon: 18.0232974,
    formatted: 'Liljeholmstorget 44, 117 43 Stockholm, Sverige',
    name: '',
    housenumber: 44,
    street: 'Liljeholmstorget',
    postcode: '117 43',
    district: 'Hägersten-Älvsjö stadsdelsområde',
    suburb: 'Liljeholmen',
    city: 'Stockholm',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.27,
    confidence_city_level: 0.3,
    confidence_street_level: 0.3,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Hammarby allé 118, 120 65 Stockholm',
    lat: 59.302115,
    lon: 18.102116,
    formatted: 'Hammarby Allé 120, 120 65 Stockholm, Sverige',
    name: '',
    housenumber: 120,
    street: 'Hammarby Allé',
    postcode: '120 65',
    district: 'Vantör',
    suburb: 'Hammarbyhöjde',
    city: 'Stockholm',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.63,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenAddresses contributors',
    attribution_license: 'BSD-3-Clause License',
    attribution_url: '',
  },
  {
    original_address: 'Värmdövägen 691, 132 35 Saltsjö-Boo',
    lat: 59.3261038,
    lon: 18.2738145,
    formatted: 'Värmdövägen, 132 35 Boo, Sverige',
    name: 'Värmdövägen',
    housenumber: '',
    street: 'Värmdövägen',
    postcode: '132 35',
    district: '',
    suburb: 'Orminge',
    city: 'Boo',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.5,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Enköpingsvägen 26B, 177 45 Järfälla',
    lat: 59.410246,
    lon: 17.8624445,
    formatted: 'Lidl, Enköpingsvägen 26 B, 177 45 Järfälla kommun, Sverige',
    name: 'Lidl',
    housenumber: '26 B',
    street: 'Enköpingsvägen',
    postcode: '177 45',
    district: 'Barkarbystaden',
    suburb: 'Barkarby',
    city: 'Järfälla kommun',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.95,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Årevägen 32, 162 61 Vällingby',
    lat: 59.360721,
    lon: 17.876058,
    formatted: 'Årevägen 32, 162 65 Stockholms kommun, Sverige',
    name: '',
    housenumber: 32,
    street: 'Årevägen',
    postcode: '162 65',
    district: 'Hässelby-Vällingby stadsdelsområde',
    suburb: 'Vällingby',
    city: 'Stockholms kommun',
    state: 'Stockholm',
    county: 'Stockholm',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenAddresses contributors',
    attribution_license: 'BSD-3-Clause License',
    attribution_url: '',
  },
  {
    original_address: 'Bussens väg 5, 122 43 Enskede',
    lat: 59.2850686,
    lon: 18.051063160321945,
    formatted: 'Lidl, Bussens väg 5, 122 43 Stockholm, Sverige',
    name: 'Lidl',
    housenumber: 5,
    street: 'Bussens väg',
    postcode: '122 43',
    district: 'Enskede-Årsta-Vantörs stadsdelsområde',
    suburb: 'Enskede',
    city: 'Stockholm',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 1,
    confidence_city_level: 1,
    confidence_street_level: 1,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
  {
    original_address: 'Värmevägen 1A, 177 57 Järfälla',
    lat: 59.4279679,
    lon: 17.846941,
    formatted: 'Värmevägen, 177 37 Järfälla kommun, Sverige',
    name: 'Värmevägen',
    housenumber: '',
    street: 'Värmevägen',
    postcode: '177 37',
    district: '',
    suburb: '',
    city: 'Järfälla kommun',
    state: '',
    county: 'Stockholms län',
    country: 'Sverige',
    country_code: 'se',
    confidence: 0.315,
    confidence_city_level: 0.63,
    confidence_street_level: 0.63,
    attribution: '© OpenStreetMap contributors',
    attribution_license: 'Open Database License',
    attribution_url: 'https://www.openstreetmap.org/copyright',
  },
];

export const getLocationsAsycn = (): Array<Address> => {
  return addresses;
};

export function addressByName(name: Adress): Address | null {
  const exists = addresses.find((a) => a.original_address === name.Adress);
  if (!exists) {
    return null;
  }
  return exists;
}

export function addressToPoint(address: Address) {
  return {
    type: 'point',
    longitude: address.lon,
    latitude: address.lat,
  };
}
